# -*- coding: utf-8 -*-
"""RAISE-2024-Data_Dynamos_AI Fear among Social Media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOKQ6KAY4DW_5PcnC0PiBGvtWfUd_d46

# **RAISE 2024** #

**Submitted by: Data Dynamos, a team comprised of  graduate students from Rutgers, The State Univeristy of New Jersey**

**Team Members: Jiatong Yang, Mrs. Shin, Mr. Hoque**

*Some team members names have been deducted for privacy protection purpose* *


**COMPETITION OVERVIEW**

Does News Media Spread Fear of AI?

Discovering dominant themes in media coverage of AI by analyzing news headlines.

**TASK**

1. Analyze these headlines to uncover the narratives surrounding AI in the media

2. Use analytical text analytics and natural language processing (NLP) techniques to extract meaningful insights from these headlines

3. Generate innovative data supported insights that deepen our understanding of media dynamics, promoting a more informed and empowered public discourse on AI.

**WORKFLOW OF THIS NOTEBOOK**

1. Data Loading and Exploration
2. Text Preprocessing
3. Exploratory Data Analysis (EDA)
4. Sentiment Analysis
5. Topic Modeling and Theme Synthesis
6. Insight Generation and Recommendations

This notebook is inspired, adapted, modified, and combined from several existing sentiment analysis projects, including but not limited to the following:

[Kaggle](https://www.kaggle.com/code/robikscube/sentiment-analysis-python-youtube-tutorial/notebook)

[FA23_ML_for_Sentiment_Classification](https://drive.google.com/file/d/1s1QsYx9Ri5DrGU6dp42aJr-Gr-AO59Us/view?usp=sharing)

[Python](https://pypi.org)

[github](https://github.com/nagypeterjob/Sentiment-Analysis-NLTK-ML-LSTM?tab=readme-ov-file)

[towardsai](https://towardsai.net/p/l/time-series-data-visualization-in-python)

[dataquest](https://www.dataquest.io/blog/tutorial-time-series-analysis-with-pandas/)

[intellspot](https://www.intellspot.com/python-visualization-tools)

[fromthegenesis](https://www.fromthegenesis.com/seaborn-python-data-visualization-tool/)

[learnpython](https://learnpython.com/blog/python-libraries-data-visualization/)

[line](https://ine.com/blog/python-visualization-libraries-you-should-know-in-2020-and-how-to-use-them)

And with the help of ChatGPT for troubleshooting
"""

# Commented out IPython magic to ensure Python compatibility.
# %pwd

"""# **1. Data Loading Exploration** #
+ Load the dataset
+ Explore the dataset to understand its structure, features, and content
+ Check for any missing values or inconsistencies in the data
"""

!pip install lmfit

pip install tabulate

# some basic packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from lmfit import Model
import statsmodels.api as sm
from tabulate import tabulate
from textblob import TextBlob

!pwd

# Read the Excel file (replace 'Dataset_3.5k.xlsx' with the actual filename)
df_og = pd.read_csv('Dataset_3.5k.csv')

# show some basic info
display(df_og.info())

# Read the Excel file (replace 'Dataset_3.5k.xlsx' with the actual filename)
df_og = pd.read_csv('Dataset_3.5k.csv')

# show some basic info
display(df_og.info())

df_og.columns
# for copying col names easier

# rename and drop other columns
# rename 'title' to 'News Article'
df_news = df_og.rename(columns={'title':'News Article'})
df_news.head()

# create a df with title only
# drop all columns except 'News Article'
df_news_title = df_news.drop(columns=['link', 'date', 'source', 'country', 'language',
       'translated_title', 'number_of_characters_title',
       'number_of_words_title', 'day_of_week', 'month', 'year', 'quarter',
       'is_weekend', 'is_holiday', 'source_type', 'final_redirected_URL',
       'domain_of_URL', 'subdomain_of_URL', 'URL_depth', 'top_level_domain',
       'url_length', 'author'])
# show it
for sentence in df_news_title['News Article'][:10]:
    for char in sentence:
        print(char, end='')
    print()

# check for null
if (df_news_title.isnull().values.any() == False):
    print('No missing value found in data')
else:
    print('MISSING VALUE IN DATA')

# optional, save comment only file
# df_comment.to_csv('ChatGPT - comment only.csv', index = False)

# convert cleaned df to list for cleaning and passing into ML later
news_list = df_news['News Article'].tolist()
news_list[:5]

# convert cleaned df to list for cleaning and passing into ML later
news_title_list = df_news['News Article'].tolist()
news_title_list[:5]

"""step summary:
+ variables:
1. df_news
2. df_news_title
3. news_list
4. news_title_list

# **2. Text Preprocessing** #
+ Non English text removal
+ Contraction Expansion
+ Lowercasing the text.
+ Tokenization and removing stopwords (common words like 'and', 'the', 'is', etc.).
+ Lemmatization or stemming to reduce words to their base or root form.
+ Removing punctuation, special characters, and numbers.

### Non English Text Removal
+ this step is important because we only analyze English text, having non English text might affect the outcomes
"""

# check what languages there are in the dataset
df_news['language'].value_counts()

# seperate English and Non English titles
df_english = df_news[df_news['language'] == 'en']
df_non_english = df_news[df_news['language'] != 'en']

df_english.head(3)

df_non_english.head(3)

"""alternative for removing non English sentences:

add another function on top of detect_language to translate them into English

### Contraction Expansion
"""

english_list = df_english['News Article'].tolist()

# expand contraction in sentences for better testing result
!pip install contractions
import contractions

# define contraction expanding function
def expand_contractions(sentence):
    expanded_sentence = contractions.fix(sentence)
    return expanded_sentence

expanded_comment_list = [expand_contractions(sentence) for sentence in english_list]
expanded_comment_list[:5]

"""### Lower Case Conversion
+ this step is important since capitalized words cannot be removed with Stopwords Removal
"""

# Convert every word into lowercase
lowercased_comment_list = [' '.join(word.lower() for word in sentence.split()) for sentence in expanded_comment_list]
lowercased_comment_list[:5]

"""### Tokenization and Stopwords Removal

import stopwords example
    
      import nltk
      from nltk.corpus import stopwords
      nltk.download('stopwords')
      print(stopwords.words('english'))
"""

# Tokenization and stopwords removal
# modified from Chatgpt generated solution
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
nltk.download('punkt') # imported since this step broke without it
nltk.download('stopwords')

# tokenization of lowercased_comment_list
words_tokened = [word_tokenize(sentence) for sentence in lowercased_comment_list]

# select and use English stopwords
stop_words = set(stopwords.words('english'))

# fliter out all stopwords in words_tokened, which are all from lowercased_comment_list
comment_no_stopwords_list = [[w for w in word_token if not w in stop_words] for word_token in words_tokened]

print('---'*80)
# print the all stopwords in nltk's stopwords package
print('NLTK stopwords word:')
print(stop_words)

# compare results before and after removing stopwords ↓
print('\nPre stopwords removal Comment:')
for wordtokens in words_tokened[:5]:
    print(wordtokens)

print('\nPost stopwords removal Comment:')
for wordtokens in comment_no_stopwords_list[:5]:
    print(wordtokens)
print('---'*80)

type(stopwords)

# reconstruct sentences for lemmatization
comment_reconstructed_list_1 = [' '.join(words) for words in comment_no_stopwords_list]
print('↓ Post stopwords removal sentence reconstruction ↓')
for sentence in comment_reconstructed_list_1[:5]:
    print(sentence)

"""### Lemmatization"""

# lemmatization with spacy
# adopted from in class notebook: NLP Basics
import spacy
nlp = spacy.load("en_core_web_sm")

lemmatized_comment_list = []
for sentence in comment_reconstructed_list_1:
    doc = nlp(sentence)
    lemmatized_sentence = [token.lemma_ for token in doc]
    lemmatized_comment_list.append(lemmatized_sentence)
# show first five
for sentence in lemmatized_comment_list[:5]:
    print(sentence)

# reconstruct sentences again for stemming
comment_reconstructed_list_2 = [' '.join(words) for words in lemmatized_comment_list]
print('↓ Post stopwords removal, lemmatization sentence reconstruction ↓')
for sentence in comment_reconstructed_list_2[:5]:
    print(sentence)

"""### Stemming"""

# stemming
from nltk.stem import PorterStemmer
# word_tokenized is already installed in previous step
# from nltk.tokenize import word_tokenize

porter_stemmer = PorterStemmer()

stemmed_comment_list = [' '.join(porter_stemmer.stem(word) for word in word_tokenize(sentence)) for sentence in comment_reconstructed_list_1]
for sentence in stemmed_comment_list[:5]:
    print(sentence)

"""### Puncuation Removal"""

# punctuation like '?' '...' occurs frequently in the text
# remove them with tools in string
import string

# define a function to remove punctuation from each sentence
def remove_punctuation(sentence):
    return ''.join(char for char in sentence if char not in string.punctuation)

comment_cleaned_list = [remove_punctuation(sentence) for sentence in stemmed_comment_list]

# Print the result
for sentence in comment_cleaned_list[:5]:
    print(sentence)

# convert cleaned comments back to a panda dataframe
# name the column title to 'Comment'
df_comment_cleaned = pd.DataFrame(comment_cleaned_list, columns = ['Comment'])
df_comment_cleaned.head()

"""**Possible improvment to the cleaning process:**
+ not reconstructing tokened words back to sentences in between steps for better runtime

# **3. EDA - Word Cloud** #
+ Generate basic statistics about the text data, such as word frequency distributions.
+ Create visualizations like word clouds, frequency histograms, and bar charts to explore the data.
+ Use N-grams (unigrams, bigrams, trigrams) to understand common phrases and expressions.
"""

from wordcloud import WordCloud, STOPWORDS
wordcloud_Chatgpt = WordCloud(stopwords = STOPWORDS,
                              width=1000,
                              height=500,
                              background_color='white').generate(' '.join(df_comment_cleaned['Comment']))
plt.figure(figsize = (10,8))
plt.imshow(wordcloud_Chatgpt, interpolation='bilinear')
plt.title('Frequent Words')
plt.axis("off")
plt.savefig('WordCloud - testing.png')
plt.show()

"""# **4. Sentiment Analysis** #
+ Utilize machine learning models, lexicon-based approaches, or pre-trained language models (like BERT or GPT) for sentiment analysis.
+ Compare the sentiment analysis results with human scoring or ground truth if available.
+ Identify interesting cases, clusters, or patterns in sentiment polarity.

## SA No.1 - VADER
#### VADER - Valence Aware Dictionary and Sentiment Reasoner
nltk pre-built tool: Sentiment Intensity Analyzer
"""

# basic SA with nltk
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

SIA = SentimentIntensityAnalyzer()

df_comment_cleaned.loc[0]

df_comment_cleaned['Comment'][0]

# SA with SIA example: analyzing first entry/row from 'Comment'
SIA.polarity_scores(df_comment_cleaned['Comment'][0])

# define a function to run SIA.polarity_scores through entire df
def SIA_analyze(text):
    SIA_sentiment_scores = SIA.polarity_scores(text)
    return SIA_sentiment_scores

"""### test on uncleaned testing dataset"""

# make a copy of df_test and save SIA results in it
df_SA1 = df_english.copy()
# run SIA_analyze function on copy with apply method
df_SA1[['negative','neutral','positive','compound']] = df_english['News Article'].apply(lambda x: pd.Series(SIA_analyze(x)))
df_SA1.head()

# determine overall sentiment of each sentence base on values in 'compound' column
# add to df_SA1 with column name 'Sentiment'
df_SA1['Sentiment'] = df_SA1['compound'].apply(lambda x: 'Positive' if x >= 0.05 else ('Negative' if x <= -0.05 else 'Neutral'))
df_SA1.head()

"""### test on cleaned testing dataset"""

# repeat steps above
df_SA1_1 = df_comment_cleaned.copy()
df_SA1_1[['negative','neutral','positive','compound']] = df_comment_cleaned['Comment'].apply(lambda x: pd.Series(SIA_analyze(x)))

# Use the compound score directly from df_SA1_1
df_SA1_1['Sentiment'] = df_SA1_1['compound'].apply(lambda x: 'Positive' if x >= 0.05 else ('Negative' if x <= -0.05 else 'Neutral'))

# Add the 'date' column from df_SA1 to df_SA1_1
df_SA1_1['date'] = df_SA1['date']

df_SA1_1.head()

"""### SA NO.1 Results Scatter Plot with Trend Line"""

# Group by date and calculate the sentiment counts
sentiment_counts = df_SA1_1.groupby('date')['Sentiment'].value_counts().unstack().fillna(0)

# Fit linear regression models for each sentiment category
x = np.arange(len(sentiment_counts)).reshape(-1, 1)

# Fit model for positive sentiment
model_positive = LinearRegression().fit(x, sentiment_counts['Positive'].values.reshape(-1, 1))

# Fit model for neutral sentiment
model_neutral = LinearRegression().fit(x, sentiment_counts['Neutral'].values.reshape(-1, 1))

# Fit model for negative sentiment
model_negative = LinearRegression().fit(x, sentiment_counts['Negative'].values.reshape(-1, 1))

# Plot the scatter plot with trend lines
plt.figure(figsize=(10, 6))

# Select only a specific number of dates to display
num_dates_to_display = 6
selected_dates = sentiment_counts.index[::len(sentiment_counts) // num_dates_to_display]

# Scatter plot for positive sentiment
plt.scatter(sentiment_counts.index, sentiment_counts['Positive'], color='blue', label='Positive', marker='o')
plt.plot(sentiment_counts.index, model_positive.predict(x), color='blue', linestyle='--')

# Scatter plot for neutral sentiment
plt.scatter(sentiment_counts.index, sentiment_counts['Neutral'], color='green', label='Neutral', marker='s')
plt.plot(sentiment_counts.index, model_neutral.predict(x), color='green', linestyle='--')

# Scatter plot for negative sentiment
plt.scatter(sentiment_counts.index, sentiment_counts['Negative'], color='red', label='Negative', marker='^')
plt.plot(sentiment_counts.index, model_negative.predict(x), color='red', linestyle='--')

# Display equations for trend lines in the middle
plt.text(0.5, 0.85, f'Positive: y = {model_positive.coef_[0][0]:.2f}x + {model_positive.intercept_[0]:.2f}', transform=plt.gca().transAxes, fontsize=10, verticalalignment='bottom', horizontalalignment='center', color='blue')
plt.text(0.5, 0.80, f'Neutral: y = {model_neutral.coef_[0][0]:.2f}x + {model_neutral.intercept_[0]:.2f}', transform=plt.gca().transAxes, fontsize=10, verticalalignment='bottom', horizontalalignment='center', color='green')
plt.text(0.5, 0.75, f'Negative: y = {model_negative.coef_[0][0]:.2f}x + {model_negative.intercept_[0]:.2f}', transform=plt.gca().transAxes, fontsize=10, verticalalignment='bottom', horizontalalignment='center', color='red')

# Set labels and title
plt.xlabel('Date')
plt.ylabel('Count of Sentiments')
plt.title('Sentiment Distribution over Time')
plt.xticks(selected_dates, rotation=45, ha='right')  # Rotate the labels for better readability
plt.legend()

# Move the legend to the upper left corner
plt.legend(loc='upper left')

# Show the plot
plt.tight_layout()
plt.show()

# Determine negative sentiment occurrences for each date
negative_counts = df_SA1_1[df_SA1_1['Sentiment'] == 'Negative']['date'].value_counts().sort_index()

# Fit a linear regression model - Second DataFrame
x = np.array(range(len(negative_counts))).reshape(-1, 1)
y = negative_counts.values.reshape(-1, 1)
model = LinearRegression()
model.fit(x, y)

# Calculate R-squared
r_squared = model.score(x, y)

# Set up the figure and subplots for scatter plots and summary tables
plt.figure(figsize=(10, 6))

# Select only a specific number of dates to display
num_dates_to_display = 6
selected_dates = negative_counts.index[::len(negative_counts) // num_dates_to_display]

# Plot DataFrame
plt.scatter(negative_counts.index, negative_counts.values, s=50, alpha=0.5, c='blue')
plt.xlabel('Date')
plt.ylabel('Count of Negative Sentiment')
plt.title('Cleaned Data')

# Select only a specific number of dates to display
num_dates_to_display = 6
selected_dates = negative_counts.index[::len(negative_counts) // num_dates_to_display]

# Set x-axis ticks
plt.xticks(selected_dates, rotation=45, ha='right')  # Rotate the labels for better readability

# Plot the trend line with equation
plt.plot(negative_counts.index, model.predict(x), color='blue', linewidth=1, alpha=0.7, linestyle='--')
plt.text(0.5, 0.9, f'Equation: y = {model.coef_[0][0]:.2f}x + {model.intercept_[0]:.2f}', transform=plt.gca().transAxes, fontsize=10, verticalalignment='top')

# Adjust layout to prevent overlap
plt.tight_layout()

# Show the combined plot
plt.show()

# Fit a linear regression model
x_with_const = sm.add_constant(x)
model = sm.OLS(y, x_with_const)
result = model.fit()

# Get the summary table as text for the second DataFrame
summary_text = result.summary().as_text()

# Split the summary table by lines
summary_lines = summary_text.split('\n')

# Print the lines of the summary table for the second DataFrame
for line in summary_lines:
    print(line)

"""### SA NO.1 Results Cumulative Chart"""

# Cumulate the sentiment counts over time
cumulative_counts = sentiment_counts.cumsum()

# Plot the cumulative bar chart
plt.figure(figsize=(10, 6))

# Plot the cumulative counts for negative sentiment with transparency
bar1 = plt.bar(cumulative_counts.index, cumulative_counts['Negative'], color='red', label='Negative', alpha=0.5)

# Plot the cumulative counts for neutral sentiment on top of negative sentiment with transparency
bar2 = plt.bar(cumulative_counts.index, cumulative_counts['Neutral'], bottom=cumulative_counts['Negative'], color='green', label='Neutral', alpha=0.5)

# Plot the cumulative counts for positive sentiment on top of negative and neutral sentiment with transparency
bar3 = plt.bar(cumulative_counts.index, cumulative_counts['Positive'],
        bottom=cumulative_counts['Negative'] + cumulative_counts['Neutral'], color='blue', label='Positive', alpha=0.5)

# Select only a specific number of dates to display
num_dates_to_display = 6
selected_dates = cumulative_counts.index[::len(cumulative_counts) // num_dates_to_display]

# Calculate and display the proportion of each sentiment category at selected dates
for date in selected_dates:
    total_count = cumulative_counts.loc[date].sum()
    y_position = 0  # Initialize the y-coordinate position for the text label
    for sentiment in ['Negative', 'Neutral', 'Positive']:
        proportion = cumulative_counts.loc[date, sentiment] / total_count
        plt.text(date, y_position + cumulative_counts.loc[date, sentiment] / 2, f'{proportion:.2f}', ha='center', fontsize=10)
        y_position += cumulative_counts.loc[date, sentiment]  # Update the y-coordinate position for the next label

# Set labels and title
plt.xlabel('Date')
plt.ylabel('Cumulative Count of Sentiments')
plt.title('Cumulative Sentiment Distribution over Time')
plt.xticks(selected_dates, rotation=45, ha='right')  # Rotate the labels for better readability

# Specify the order of labels in the legend
handles = [bar3, bar2, bar1]
labels = ['Positive', 'Neutral', 'Negative']
plt.legend(handles, labels)

# Show the plot
plt.tight_layout()
plt.show()

"""### SA NO.1 Results 100% Cumulative Chart"""

# Calculate the cumulative sum of sentiment counts
cumulative_counts = sentiment_counts.cumsum()

# Normalize the cumulative counts to obtain proportions
proportions = cumulative_counts.div(cumulative_counts.sum(axis=1), axis=0)

# Plot the 100% stacked vertical bar chart
plt.figure(figsize=(10, 6))

# Plot the bars for negative sentiment with transparency
bar1 = plt.bar(proportions.index, proportions['Negative'], color='red', label='Negative', alpha=0.5)

# Plot the bars for neutral sentiment on top of negative sentiment with transparency
bar2 = plt.bar(proportions.index, proportions['Neutral'], bottom=proportions['Negative'], color='green', label='Neutral', alpha=0.5)

# Plot the bars for positive sentiment on top of negative and neutral sentiment with transparency
bar3 = plt.bar(proportions.index, proportions['Positive'],
        bottom=proportions['Negative'] + proportions['Neutral'], color='blue', label='Positive', alpha=0.5)

# Select only a specific number of dates to display
num_dates_to_display = 6
selected_dates = proportions.index[::len(proportions) // num_dates_to_display]

# Calculate and display the proportion of each sentiment category at selected dates
for date in selected_dates:
    total_count = proportions.loc[date].sum()
    y_position = 0  # Initialize the y-coordinate position for the text label
    for sentiment in ['Negative', 'Neutral', 'Positive']:
        proportion = proportions.loc[date, sentiment]
        plt.text(date, y_position + proportion / 2, f'{proportion:.2f}', ha='center', fontsize=10)
        y_position += proportion  # Update the y-coordinate position for the next label

# Set labels and title
plt.xlabel('Date')
plt.ylabel('Proportion of Sentiments')
plt.title('Proportion of Sentiment Distribution over Time')

# Specify the order of labels in the legend to match the bar order
handles = [bar3, bar2, bar1]
labels = ['Positive', 'Neutral', 'Negative']
plt.legend(handles, labels)

# Show the plot
plt.xticks(selected_dates, rotation=45, ha='right')  # Rotate the labels for better readability
plt.tight_layout()
plt.show()

"""Summary:
+ While changes in sentiment distributions are observed, further investigation and contextual information are essential for a nuanced understanding of sentiment trends and their underlying drivers.

## SA No.2 - TextBlob
"""

# https://textblob.readthedocs.io/en/dev/

# example
text = df_english['News Article'][77]
TB = TextBlob(text)
print(text)
print(' --- '*80)
print(TB.sentiment)
print(' --- '*80)
print(TB.sentiment.polarity)

# polarity range from -1 to 1
# define a funtion to read through the entire df
def TextBlob_Analyze(text):
   TB = TextBlob(text)
   sentiment_polarity = TB.sentiment.polarity
   if sentiment_polarity > 0:
    return 'Positive'
   elif sentiment_polarity < 0:
    return 'Negative'
   else:
    return 'Neutral'

"""### test on uncleaned testing dataset"""

df_SA2 = df_english.copy()
df_SA2['Sentiment'] = df_english['News Article'].apply(TextBlob_Analyze)
df_SA2.head()

"""### test on cleaned testing dataset"""

# repeat steps above
df_SA2_1 = df_comment_cleaned.copy()
df_SA2_1['Sentiment'] = df_comment_cleaned['Comment'].apply(TextBlob_Analyze)
df_SA2_1.head()

"""## SA NO.2 Results Pie Chart"""

# pie chart displaying over sentiment results
# import matplotlib.pyplot as plt
sentiment_counts = df_SA2['Sentiment'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=90, colors=['green', 'red', 'yellow'])
plt.title('Sentiment Distribution - Uncleaned Test')
plt.savefig('Result_2 - TextBlob.png')
plt.show()

# pie chart displaying over sentiment results
# import matplotlib.pyplot as plt
sentiment_counts = df_SA2_1['Sentiment'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=90, colors=['green', 'red', 'yellow'])
plt.title('Sentiment Distribution - Cleaned Test')
plt.savefig('Result_2_clean - TextBlob.png')
plt.show()

"""# **5. Topic Modeling and Theme Synthesis** #
+ Apply topic modeling techniques like Latent Dirichlet Allocation (LDA) or Non-Negative Matrix Factorization (NMF) to identify dominant topics in the news headlines.
+ Explore the interconnections between topics to synthesize overarching themes.
+ Visualize topic distributions and topic-word associations using tools like word clouds and network graphs.

## Prepare train_1 dataframe
"""

# encoding with uft-8 doesn't work on train_1, use one of the following encoding methods
# train_1 = pd.read_csv('train_1.csv', encoding = 'ISO-8859-1')
# train_1 = pd.read_csv('train_1.csv', encoding = 'unicode_escape')
train_1 = pd.read_csv('train_1.csv', encoding = 'unicode_escape')
train_1.info()

# we only need 'text' and 'sentiment' columns
train_1 = train_1.drop(columns=['textID','selected_text','Time of Tweet','Age of User','Country','Population -2020','Land Area (Km²)','Density (P/Km²)'])
train_1.head()

# see how many level of sentiment there are in train_1
print('The sentiments are:', train_1['sentiment'].unique())
print('\nLevels of sentiments:',train_1['sentiment'].nunique())

"""Since train_1 has three levels of sentiments, model_1 is also going to yield three levels of sentiments"""

# from info() above, we can see there is one missing value in text column
# check for missing value (NaN) to ensure models can run
train_1.isnull().sum()

# locate the missing value
missing_value = train_1.isnull()
missing_row = train_1[missing_value.any(axis=1)] # check rows
missing_column = train_1.columns[missing_value.any()] # check columns

print('Rows with missing values:')
print(missing_row)
print('\n',missing_row.index)
print('\nColumns with missing values:')
print(missing_column)

train_1.iloc[missing_row.index]

# drop the row with missing value
train_1 = train_1.drop(missing_row.index)
train_1.isnull().sum()

# expand contraction in sentences for better training result
# !pip install contractions
# import contractions

### this function is already defined in testing data cleaning process ###
# def expand_contractions(sentence):
    # expanded_sentence = contractions.fix(sentence)
    # return expanded_sentence

train_1['text_formalized'] = train_1['text'].apply(expand_contractions)
train_1.head()

# remove puntuations and other meaningless characters
# copied from in-class example
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) +\
        ' '.join(emoticons).replace('-', '')
    return text

train_1['text_cleaned'] = train_1['text_formalized'].apply(preprocessor)
train_1.head()

# check for missing value one last time
train_1.info()
print('---'*80)
if (train_1.isnull().values.any() == False):
    print('No missing value found in data')
else:
    print('MISSING VALUE IN DATA')

train_1.head()

"""## EDA - train_1"""

# since we are using STOPWORDS in wordcloud package, let's plot based on 'text' instead of 'text_cleaned'
# from wordcloud import WordCloud, STOPWORDS
wordcloud_train_1 = WordCloud(stopwords = STOPWORDS,
                              width=1000,
                              height=500,
                              background_color='white').generate(" ".join(train_1['text']))
plt.figure(figsize = (9,8))
plt.imshow(wordcloud_train_1, interpolation='bilinear')
plt.title("Frequent Words")
plt.axis("off")
plt.savefig('WordCloud - training.png')
plt.show()

"""## SA No.3 / ML Model 1"""

# modified from ChatGPT solution
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score
from sklearn.naive_bayes import MultinomialNB

X = train_1['text_cleaned']
y = train_1['sentiment']

# extract feature vectors
vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

# mapping sentiments to index
label_mapping = {'positive': 0, 'negative': 1, 'neutral': 2}
y_encoded = y.map(label_mapping)

# use 90% to train and 10% to test model
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y_encoded, test_size=0.1, random_state=88)
# constructing model
model = MultinomialNB()
model.fit(X_train, y_train)

# accuracy test
y_pred = model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

# predict results using this model
# use cleaned comments from Preparation step
comment_cleaned_vectorized = vectorizer.transform(comment_cleaned_list)
predictions = model.predict(comment_cleaned_vectorized)

type(predictions)

# convert 0,1,2 to corresponding sentiments:'positive', 'negative', 'neutral'
sentiment_mapping = {0: 'Positive', 1: 'Negative', 2: 'Neutral'}
convert_sentiment = np.vectorize(lambda x: sentiment_mapping[x])
converted_array = convert_sentiment(predictions)

# convert array to list and add back to a copy of df_english_comment
df_SA3 = df_english.copy()
converted_list = converted_array.tolist()
df_SA3['Sentiment'] = converted_list
df_SA3.head()

"""## SA No.3 / ML Model 1 Results Pie Chart"""

# pie chart displaying over sentiment results
# import matplotlib.pyplot as plt
sentiment_counts = df_SA3['Sentiment'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=90, colors=['green', 'red', 'yellow'])
plt.title('Sentiment Distribution')
plt.savefig('Result_3 - Naïve Bayes classifier.png')
plt.show()

"""## SA No.4 / ML Model 2"""

# avoid over importing
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC

# decide training and testing portion
X_train, X_test, y_train, y_test = train_test_split(train_1['text_cleaned'], train_1['sentiment'], test_size=0.1, random_state=99)

# use the feature extraction as model 1
# extract feature vectors
vectorizer = TfidfVectorizer(stop_words='english')
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

# constructing SVM model
# svm_model = SVC()
svm_model = SVC(kernel='linear', random_state=99)
svm_model.fit(X_train_vectorized, y_train)

# evaluate accuracy
y_pred = svm_model.predict(X_test_vectorized)
accuracy_test = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f'Accuracy: {accuracy_test:.2f}')
print('Classification Report:\n', report)

# predict for testing dataset
comment_cleaned_vectorized = vectorizer.transform(comment_cleaned_list)
predictions_SVM = svm_model.predict(comment_cleaned_vectorized)

type(predictions_SVM)

# actually we do not have to convert array to_list to add it to df_SA4
df_SA4 = df_english.copy()
df_SA4['Sentiment'] = predictions_SVM
df_SA4.head()

"""## SA No.4 / ML Model 2 Results Pie Chart"""

# pie chart displaying over sentiment results
import matplotlib.pyplot as plt
sentiment_counts = df_SA4['Sentiment'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=90, colors=['green', 'red', 'yellow'])
plt.title('Sentiment Distribution')
plt.savefig('Result_4 - SVM.png')
plt.show()

"""# Results Comparison"""

print(df_english.info())
print('---'*80)
print(df_comment_cleaned.info())
print('---'*80)
print(train_1['text'].info())

import matplotlib.image as mpimg

pies = ['Result_2_clean - TextBlob.png',
        'Result_2 - TextBlob.png',
        'Result_3 - Naïve Bayes classifier.png',
        'Result_4 - SVM.png']

pies_names = ['VADER','TextBlob','Naïve Bayes','SVM']

fig, axes = plt.subplots(1, 4, figsize=(15, 8)) # 1 row and 4 columns

for i, (paths, names) in enumerate(zip(pies, pies_names)):
    four_pies = mpimg.imread(paths)
    axes[i].imshow(four_pies)
    axes[i].axis('off')  # turn off axix for a cleaner view
    axes[i].set_title(names)

plt.tight_layout() # adjust layout to prevent overlapping
plt.savefig('Results Comparison - Uncleaned.png')
plt.show()

pies_2 = ['Result_2_clean - TextBlob.png',
        'Result_2_clean - TextBlob.png',
        'Result_3 - Naïve Bayes classifier.png',
        'Result_4 - SVM.png']

pies_names = ['VADER','TextBlob','Naïve Bayes','SVM']

fig, axes = plt.subplots(1, 4, figsize=(15, 8)) # 1 row and 4 columns

for i, (paths, names) in enumerate(zip(pies_2, pies_names)):
    four_pies = mpimg.imread(paths)
    axes[i].imshow(four_pies)
    axes[i].axis('off')  # turn off axix for a cleaner view
    axes[i].set_title(names)

plt.tight_layout() # adjust layout to prevent overlapping
plt.savefig('Results Comparison - cleaned.png')
plt.show()

"""# **6. Findings and Recommendations** #

**It appears that the news media is not predominantly spreading fear of AI, at least not in the dataset we've analyzed. However, it's essential to consider the limitations of the dataset and the possibility that fear-based narratives may exist in other contexts or datasets not included in our analysis.**
"""